-- CreateTable
CREATE TABLE "User" (
  "userId" INT GENERATED BY DEFAULT AS IDENTITY,
    "username" VARCHAR(14) NOT NULL DEFAULT 'user',
    "email" VARCHAR(254) NOT NULL,
    "hash" VARCHAR(64) NOT NULL,
    "salt" VARCHAR(64) NOT NULL,
    "role" TEXT NOT NULL DEFAULT 'user',

    CONSTRAINT "User_pkey" PRIMARY KEY ("userId")
);

-- CreateTable
CREATE TABLE "WeatherLayouts" (
    "weatherCompId" INTEGER NOT NULL,
    "userId" INTEGER NOT NULL,
    "dataGrid" JSONB NOT NULL,

    CONSTRAINT "WeatherLayouts_pkey" PRIMARY KEY ("weatherCompId","userId")
);

-- CreateTable
CREATE TABLE "RefreshToken" (
    "id" SERIAL NOT NULL,
    "token" TEXT NOT NULL,
    "userId" INTEGER NOT NULL,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "RefreshToken_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

-- CreateIndex
CREATE UNIQUE INDEX "User_hash_key" ON "User"("hash");

-- CreateIndex
CREATE UNIQUE INDEX "User_salt_key" ON "User"("salt");

-- CreateIndex
CREATE UNIQUE INDEX "RefreshToken_token_key" ON "RefreshToken"("token");

-- AddForeignKey
ALTER TABLE "WeatherLayouts" ADD CONSTRAINT "WeatherLayouts_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("userId")  ON DELETE CASCADE ON UPDATE CASCADE;


-- AddForeignKey
ALTER TABLE "RefreshToken" ADD CONSTRAINT "RefreshToken_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("userId") ON DELETE CASCADE ON UPDATE CASCADE;
