name: weather

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    environment: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Start containers in detached mode
      - name: Start backend
        run: docker compose up -d
        working-directory: ./backend
        env:
          ACCESS_SECRET_TOKEN: ${{ secrets.ACCESS_SECRET_TOKEN }}
          REFRESH_SECRET_TOKEN: ${{ secrets.REFRESH_SECRET_TOKEN }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Start frontend
        run: docker compose up -d
        working-directory: ./frontend
        env:
          VITE_AUTH_HOST: ${{ secrets.VITE_AUTH_HOST }}
          VITE_LAYOUT_HOST: ${{ secrets.VITE_LAYOUT_HOST }}
          VITE_BACKEND_HOST: ${{ secrets.VITE_BACKEND_HOST }}
          VITE_WEATHER_API_KEY: ${{ secrets.VITE_WEATHER_API_KEY }}
          VITE_WEATHER_HOST: ${{ secrets.VITE_WEATHER_HOST }}
          VITE_APP_VERSION: ${{ secrets.VITE_APP_VERSION }}
          
      # Playwright install
      - run: npm install
      - run: npx playwright install --with-deps

      # Run tests
      - name: E2E tests
        run: npx playwright test docker stop backend-ci frontend-ci || true docker rm backend-ci frontend-ci || true
